'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsciashop
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", ConfigurationName:="wsciashop.wsIntegracaoSoap")>  _
    Public Interface wsIntegracaoSoap
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/Pedidos", ReplyAction:="*")>  _
        Function Pedidos(ByVal request As wsciashop.PedidosRequest) As wsciashop.PedidosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/ConfirmaPedidos", ReplyAction:="*")>  _
        Function ConfirmaPedidos(ByVal request As wsciashop.ConfirmaPedidosRequest) As wsciashop.ConfirmaPedidosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/StatusPedido", ReplyAction:="*")>  _
        Function StatusPedido(ByVal request As wsciashop.StatusPedidoRequest) As wsciashop.StatusPedidoResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/ConsultaStatusPedidos", ReplyAction:="*")>  _
        Function ConsultaStatusPedidos(ByVal request As wsciashop.ConsultaStatusPedidosRequest) As wsciashop.ConsultaStatusPedidosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/Compradores", ReplyAction:="*")>  _
        Function Compradores(ByVal request As wsciashop.CompradoresRequest) As wsciashop.CompradoresResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/ConfirmaCompradores", ReplyAction:="*")>  _
        Function ConfirmaCompradores(ByVal request As wsciashop.ConfirmaCompradoresRequest) As wsciashop.ConfirmaCompradoresResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/Produtos", ReplyAction:="*")>  _
        Function Produtos(ByVal request As wsciashop.ProdutosRequest) As wsciashop.ProdutosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/Variantes", ReplyAction:="*")>  _
        Function Variantes(ByVal request As wsciashop.VariantesRequest) As wsciashop.VariantesResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/Departamentos", ReplyAction:="*")>  _
        Function Departamentos(ByVal request As wsciashop.DepartamentosRequest) As wsciashop.DepartamentosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/DepartamentosProdutos", ReplyAction:="*")>  _
        Function DepartamentosProdutos(ByVal request As wsciashop.DepartamentosProdutosRequest) As wsciashop.DepartamentosProdutosResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/AtualizaEstoque", ReplyAction:="*")>  _
        Function AtualizaEstoque(ByVal request As wsciashop.AtualizaEstoqueRequest) As wsciashop.AtualizaEstoqueResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/EnviaImagem", ReplyAction:="*")>  _
        Function EnviaImagem(ByVal request As wsciashop.EnviaImagemRequest) As wsciashop.EnviaImagemResponse
        
        'CODEGEN: Generating message contract since element name login from namespace https://wssmb.ciashop.com.br/WSIntegSMB is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="https://wssmb.ciashop.com.br/WSIntegSMB/ConfirmaDados", ReplyAction:="*")>  _
        Function ConfirmaDados(ByVal request As wsciashop.ConfirmaDadosRequest) As wsciashop.ConfirmaDadosResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Pedidos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.PedidosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.PedidosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class PedidosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PedidosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PedidosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.PedidosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.PedidosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class PedidosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PedidosResult As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PedidosResult As Integer, ByVal xml As String)
            MyBase.New
            Me.PedidosResult = PedidosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaPedidosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaPedidos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaPedidosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaPedidosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaPedidosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaPedidosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaPedidosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaPedidosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaPedidosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaPedidosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ConfirmaPedidosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConfirmaPedidosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.ConfirmaPedidosResult = ConfirmaPedidosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class StatusPedidoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="StatusPedido", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.StatusPedidoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.StatusPedidoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class StatusPedidoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class StatusPedidoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="StatusPedidoResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.StatusPedidoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.StatusPedidoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class StatusPedidoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public StatusPedidoResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal StatusPedidoResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.StatusPedidoResult = StatusPedidoResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaStatusPedidosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaStatusPedidos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConsultaStatusPedidosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConsultaStatusPedidosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConsultaStatusPedidosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultaStatusPedidosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultaStatusPedidosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConsultaStatusPedidosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConsultaStatusPedidosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConsultaStatusPedidosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ConsultaStatusPedidosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultaStatusPedidosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.ConsultaStatusPedidosResult = ConsultaStatusPedidosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompradoresRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Compradores", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.CompradoresRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.CompradoresRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class CompradoresRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CompradoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CompradoresResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.CompradoresResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.CompradoresResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class CompradoresResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CompradoresResult As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CompradoresResult As Integer, ByVal xml As String)
            MyBase.New
            Me.CompradoresResult = CompradoresResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaCompradoresRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaCompradores", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaCompradoresRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaCompradoresRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaCompradoresRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaCompradoresResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaCompradoresResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaCompradoresResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaCompradoresResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaCompradoresResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ConfirmaCompradoresResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConfirmaCompradoresResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.ConfirmaCompradoresResult = ConfirmaCompradoresResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ProdutosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Produtos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ProdutosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ProdutosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ProdutosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ProdutosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProdutosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ProdutosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ProdutosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ProdutosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ProdutosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ProdutosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.ProdutosResult = ProdutosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VariantesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Variantes", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.VariantesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.VariantesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class VariantesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VariantesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VariantesResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.VariantesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.VariantesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class VariantesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public VariantesResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VariantesResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.VariantesResult = VariantesResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DepartamentosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Departamentos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.DepartamentosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.DepartamentosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class DepartamentosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DepartamentosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DepartamentosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.DepartamentosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.DepartamentosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class DepartamentosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public DepartamentosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DepartamentosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.DepartamentosResult = DepartamentosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DepartamentosProdutosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DepartamentosProdutos", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.DepartamentosProdutosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.DepartamentosProdutosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class DepartamentosProdutosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DepartamentosProdutosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DepartamentosProdutosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.DepartamentosProdutosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.DepartamentosProdutosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class DepartamentosProdutosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public DepartamentosProdutosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DepartamentosProdutosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.DepartamentosProdutosResult = DepartamentosProdutosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaEstoqueRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AtualizaEstoque", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.AtualizaEstoqueRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.AtualizaEstoqueRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class AtualizaEstoqueRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AtualizaEstoqueResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AtualizaEstoqueResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.AtualizaEstoqueResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.AtualizaEstoqueResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class AtualizaEstoqueResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AtualizaEstoqueResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AtualizaEstoqueResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.AtualizaEstoqueResult = AtualizaEstoqueResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviaImagemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviaImagem", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.EnviaImagemRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.EnviaImagemRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class EnviaImagemRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public stream() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public caminho As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public nome_arquivo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public sku As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public idx As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public tipo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal stream() As Byte, ByVal caminho As String, ByVal nome_arquivo As String, ByVal sku As String, ByVal idx As Integer, ByVal tipo As String, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.stream = stream
            Me.caminho = caminho
            Me.nome_arquivo = nome_arquivo
            Me.sku = sku
            Me.idx = idx
            Me.tipo = tipo
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviaImagemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviaImagemResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.EnviaImagemResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.EnviaImagemResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class EnviaImagemResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviaImagemResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviaImagemResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.EnviaImagemResult = EnviaImagemResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaDadosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaDados", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaDadosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaDadosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaDadosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public login As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public confirmaLeitura As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal login As String, ByVal password As String, ByVal confirmaLeitura As Boolean, ByVal xml As String)
            MyBase.New
            Me.login = login
            Me.password = password
            Me.confirmaLeitura = confirmaLeitura
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConfirmaDadosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConfirmaDadosResponse", [Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB", Order:=0)>  _
        Public Body As wsciashop.ConfirmaDadosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsciashop.ConfirmaDadosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://wssmb.ciashop.com.br/WSIntegSMB")>  _
    Partial Public Class ConfirmaDadosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ConfirmaDadosResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConfirmaDadosResult As Boolean, ByVal xml As String)
            MyBase.New
            Me.ConfirmaDadosResult = ConfirmaDadosResult
            Me.xml = xml
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsIntegracaoSoapChannel
        Inherits wsciashop.wsIntegracaoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsIntegracaoSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsciashop.wsIntegracaoSoap)
        Implements wsciashop.wsIntegracaoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_Pedidos(ByVal request As wsciashop.PedidosRequest) As wsciashop.PedidosResponse Implements wsciashop.wsIntegracaoSoap.Pedidos
            Return MyBase.Channel.Pedidos(request)
        End Function
        
        Public Function Pedidos(ByVal login As String, ByVal password As String, ByRef xml As String) As Integer
            Dim inValue As wsciashop.PedidosRequest = New wsciashop.PedidosRequest()
            inValue.Body = New wsciashop.PedidosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.PedidosResponse = CType(Me,wsciashop.wsIntegracaoSoap).Pedidos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.PedidosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_ConfirmaPedidos(ByVal request As wsciashop.ConfirmaPedidosRequest) As wsciashop.ConfirmaPedidosResponse Implements wsciashop.wsIntegracaoSoap.ConfirmaPedidos
            Return MyBase.Channel.ConfirmaPedidos(request)
        End Function
        
        Public Function ConfirmaPedidos(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.ConfirmaPedidosRequest = New wsciashop.ConfirmaPedidosRequest()
            inValue.Body = New wsciashop.ConfirmaPedidosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.ConfirmaPedidosResponse = CType(Me,wsciashop.wsIntegracaoSoap).ConfirmaPedidos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.ConfirmaPedidosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_StatusPedido(ByVal request As wsciashop.StatusPedidoRequest) As wsciashop.StatusPedidoResponse Implements wsciashop.wsIntegracaoSoap.StatusPedido
            Return MyBase.Channel.StatusPedido(request)
        End Function
        
        Public Function StatusPedido(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.StatusPedidoRequest = New wsciashop.StatusPedidoRequest()
            inValue.Body = New wsciashop.StatusPedidoRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.StatusPedidoResponse = CType(Me,wsciashop.wsIntegracaoSoap).StatusPedido(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.StatusPedidoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_ConsultaStatusPedidos(ByVal request As wsciashop.ConsultaStatusPedidosRequest) As wsciashop.ConsultaStatusPedidosResponse Implements wsciashop.wsIntegracaoSoap.ConsultaStatusPedidos
            Return MyBase.Channel.ConsultaStatusPedidos(request)
        End Function
        
        Public Function ConsultaStatusPedidos(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.ConsultaStatusPedidosRequest = New wsciashop.ConsultaStatusPedidosRequest()
            inValue.Body = New wsciashop.ConsultaStatusPedidosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.ConsultaStatusPedidosResponse = CType(Me,wsciashop.wsIntegracaoSoap).ConsultaStatusPedidos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.ConsultaStatusPedidosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_Compradores(ByVal request As wsciashop.CompradoresRequest) As wsciashop.CompradoresResponse Implements wsciashop.wsIntegracaoSoap.Compradores
            Return MyBase.Channel.Compradores(request)
        End Function
        
        Public Function Compradores(ByVal login As String, ByVal password As String, ByRef xml As String) As Integer
            Dim inValue As wsciashop.CompradoresRequest = New wsciashop.CompradoresRequest()
            inValue.Body = New wsciashop.CompradoresRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.CompradoresResponse = CType(Me,wsciashop.wsIntegracaoSoap).Compradores(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.CompradoresResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_ConfirmaCompradores(ByVal request As wsciashop.ConfirmaCompradoresRequest) As wsciashop.ConfirmaCompradoresResponse Implements wsciashop.wsIntegracaoSoap.ConfirmaCompradores
            Return MyBase.Channel.ConfirmaCompradores(request)
        End Function
        
        Public Function ConfirmaCompradores(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.ConfirmaCompradoresRequest = New wsciashop.ConfirmaCompradoresRequest()
            inValue.Body = New wsciashop.ConfirmaCompradoresRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.ConfirmaCompradoresResponse = CType(Me,wsciashop.wsIntegracaoSoap).ConfirmaCompradores(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.ConfirmaCompradoresResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_Produtos(ByVal request As wsciashop.ProdutosRequest) As wsciashop.ProdutosResponse Implements wsciashop.wsIntegracaoSoap.Produtos
            Return MyBase.Channel.Produtos(request)
        End Function
        
        Public Function Produtos(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.ProdutosRequest = New wsciashop.ProdutosRequest()
            inValue.Body = New wsciashop.ProdutosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.ProdutosResponse = CType(Me,wsciashop.wsIntegracaoSoap).Produtos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.ProdutosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_Variantes(ByVal request As wsciashop.VariantesRequest) As wsciashop.VariantesResponse Implements wsciashop.wsIntegracaoSoap.Variantes
            Return MyBase.Channel.Variantes(request)
        End Function
        
        Public Function Variantes(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.VariantesRequest = New wsciashop.VariantesRequest()
            inValue.Body = New wsciashop.VariantesRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.VariantesResponse = CType(Me,wsciashop.wsIntegracaoSoap).Variantes(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.VariantesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_Departamentos(ByVal request As wsciashop.DepartamentosRequest) As wsciashop.DepartamentosResponse Implements wsciashop.wsIntegracaoSoap.Departamentos
            Return MyBase.Channel.Departamentos(request)
        End Function
        
        Public Function Departamentos(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.DepartamentosRequest = New wsciashop.DepartamentosRequest()
            inValue.Body = New wsciashop.DepartamentosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.DepartamentosResponse = CType(Me,wsciashop.wsIntegracaoSoap).Departamentos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.DepartamentosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_DepartamentosProdutos(ByVal request As wsciashop.DepartamentosProdutosRequest) As wsciashop.DepartamentosProdutosResponse Implements wsciashop.wsIntegracaoSoap.DepartamentosProdutos
            Return MyBase.Channel.DepartamentosProdutos(request)
        End Function
        
        Public Function DepartamentosProdutos(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.DepartamentosProdutosRequest = New wsciashop.DepartamentosProdutosRequest()
            inValue.Body = New wsciashop.DepartamentosProdutosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.DepartamentosProdutosResponse = CType(Me,wsciashop.wsIntegracaoSoap).DepartamentosProdutos(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.DepartamentosProdutosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_AtualizaEstoque(ByVal request As wsciashop.AtualizaEstoqueRequest) As wsciashop.AtualizaEstoqueResponse Implements wsciashop.wsIntegracaoSoap.AtualizaEstoque
            Return MyBase.Channel.AtualizaEstoque(request)
        End Function
        
        Public Function AtualizaEstoque(ByVal login As String, ByVal password As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.AtualizaEstoqueRequest = New wsciashop.AtualizaEstoqueRequest()
            inValue.Body = New wsciashop.AtualizaEstoqueRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.xml = xml
            Dim retVal As wsciashop.AtualizaEstoqueResponse = CType(Me,wsciashop.wsIntegracaoSoap).AtualizaEstoque(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.AtualizaEstoqueResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_EnviaImagem(ByVal request As wsciashop.EnviaImagemRequest) As wsciashop.EnviaImagemResponse Implements wsciashop.wsIntegracaoSoap.EnviaImagem
            Return MyBase.Channel.EnviaImagem(request)
        End Function
        
        Public Function EnviaImagem(ByVal login As String, ByVal password As String, ByVal stream() As Byte, ByVal caminho As String, ByVal nome_arquivo As String, ByVal sku As String, ByVal idx As Integer, ByVal tipo As String, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.EnviaImagemRequest = New wsciashop.EnviaImagemRequest()
            inValue.Body = New wsciashop.EnviaImagemRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.stream = stream
            inValue.Body.caminho = caminho
            inValue.Body.nome_arquivo = nome_arquivo
            inValue.Body.sku = sku
            inValue.Body.idx = idx
            inValue.Body.tipo = tipo
            inValue.Body.xml = xml
            Dim retVal As wsciashop.EnviaImagemResponse = CType(Me,wsciashop.wsIntegracaoSoap).EnviaImagem(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.EnviaImagemResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsciashop_wsIntegracaoSoap_ConfirmaDados(ByVal request As wsciashop.ConfirmaDadosRequest) As wsciashop.ConfirmaDadosResponse Implements wsciashop.wsIntegracaoSoap.ConfirmaDados
            Return MyBase.Channel.ConfirmaDados(request)
        End Function
        
        Public Function ConfirmaDados(ByVal login As String, ByVal password As String, ByVal confirmaLeitura As Boolean, ByRef xml As String) As Boolean
            Dim inValue As wsciashop.ConfirmaDadosRequest = New wsciashop.ConfirmaDadosRequest()
            inValue.Body = New wsciashop.ConfirmaDadosRequestBody()
            inValue.Body.login = login
            inValue.Body.password = password
            inValue.Body.confirmaLeitura = confirmaLeitura
            inValue.Body.xml = xml
            Dim retVal As wsciashop.ConfirmaDadosResponse = CType(Me,wsciashop.wsIntegracaoSoap).ConfirmaDados(inValue)
            xml = retVal.Body.xml
            Return retVal.Body.ConfirmaDadosResult
        End Function
    End Class
End Namespace
